layout: {zmk_keyboard: glove80}
layers:
  default:
    - F1
    - F2
    - F3
    - F4
    - F5
    - F6
    - F7
    - F8
    - F9
    - F10
    - F11
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
    - '7'
    - '8'
    - '9'
    - '0'
    - F12
    - '-'
    - Q
    - W
    - F
    - P
    - B
    - J
    - L
    - U
    - Y
    - ;
    - \
    - '='
    - {t: A, h: Gui}
    - {t: R, h: Alt}
    - {t: S, h: Ctrl}
    - {t: T, h: Shift}
    - G
    - M
    - {t: N, h: Shift}
    - {t: E, h: Ctrl}
    - {t: I, h: Alt}
    - {t: O, h: Gui}
    - ''''
    - '`'
    - Z
    - X
    - C
    - D
    - V
    - Ctrl
    - Alt
    - {t: '&ld', h: special}
    - Gui
    - Ctrl
    - Tab
    - K
    - H
    - ','
    - .
    - /
    - PgUp
    - {t: '&rgb_ug_status_macro', h: magic}
    - Home
    - End
    - {t: '[', right: '{'}
    - {t: ']', right: '}'}
    - {t: BACKSPACE, s: DELETE}
    - {t: Esc, h: symbol}
    - {t: Shift, h: sticky, s: Caps Word}
    - Alt
    - Enter
    - Spc
    - ←
    - ↓
    - ↑
    - →
    - PgDn
  mouse_slow:
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - PgUp
    - Scroll ↑
    - Mouse ↑
    - Scroll ↓
    - PgDn
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - Scroll ←
    - Mouse ←
    - Mouse ↓
    - Mouse →
    - Scroll →
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - {t: Esc, h: mouse_fast}
    - ''
    - {t: default, h: toggle}
    - ''
    - ''
    - Right Click
    - ''
    - Left Click
    - Middle Click
    - Right Click
    - ''
    - ''
    - {type: trans}
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - Left Click
    - ''
    - ''
    - ''
    - ''
    - ''
  mouse_fast:
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: held}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
  gaming:
    - Esc
    - P
    - O
    - N
    - B
    - F1
    - F2
    - F3
    - F4
    - F5
    - M
    - '6'
    - '7'
    - '8'
    - '9'
    - '0'
    - F6
    - F7
    - F8
    - F9
    - F10
    - F11
    - I
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - Y
    - U
    - I
    - O
    - P
    - F12
    - T
    - Tab
    - Q
    - W
    - E
    - R
    - H
    - J
    - K
    - L
    - ;
    - ''''
    - G
    - Shift
    - A
    - S
    - D
    - F
    - ''
    - ''
    - {t: exp, h: toggle}
    - ''
    - ''
    - Tab
    - N
    - M
    - ','
    - .
    - /
    - \
    - {type: trans}
    - Ctrl
    - Z
    - X
    - C
    - {t: BACKSPACE, s: DELETE}
    - ''
    - ''
    - ''
    - Enter
    - Spc
    - '-'
    - {t: '[', right: '{'}
    - {t: ']', right: '}'}
    - '='
    - '`'
  symbol:
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - AltGr+Q
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - Shift
    - ''
    - ''
    - ''
    - ''
    - AltGr+T
    - AltGr+W
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - {type: held}
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
  special:
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - $$mdi:volume-off$$
    - $$mdi:volume-medium$$
    - $$mdi:volume-high$$
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - $$mdi:play-pause$$
    - $$mdi:skip-backward$$
    - $$mdi:skip-forward$$
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: held}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
  exp:
    - {t: '1', s: F1}
    - {t: '2', s: F2}
    - {t: '3', s: F3}
    - {t: '4', s: F4}
    - {t: '5', s: F5}
    - {t: '6', s: F6}
    - {t: '7', s: F7}
    - {t: '8', s: F8}
    - {t: '9', s: F9}
    - {t: '0', s: F10}
    - {t: $, s: '`'}
    - +
    - {t: '[', right: '{'}
    - '{'
    - (
    - {t: '&', s: '|'}
    - '='
    - )
    - '}'
    - {t: ']', right: '}'}
    - {t: '*', s: \}
    - '!'
    - Tab
    - Q
    - W
    - F
    - P
    - B
    - J
    - L
    - U
    - Y
    - ;
    - '-'
    - Esc
    - {t: A, h: Gui}
    - {t: R, h: Alt}
    - {t: S, h: Ctrl}
    - {t: T, h: Shift}
    - G
    - M
    - {t: N, h: Shift}
    - {t: E, h: Ctrl}
    - {t: I, h: Alt}
    - {t: O, h: Gui}
    - ''''
    - '`'
    - Z
    - X
    - C
    - D
    - V
    - {t: Shift, h: sticky, s: Caps Word}
    - Ctrl
    - {t: default, h: toggle}
    - Gui
    - Ctrl
    - Tab
    - K
    - H
    - ','
    - .
    - /
    - {t: PgUp, s: F11}
    - {t: '&rgb_ug_status_macro', h: magic}
    - Home
    - End
    - {t: '[', right: '{'}
    - {t: ']', right: '}'}
    - {t: BACKSPACE, s: DELETE}
    - {t: Esc, h: symbol}
    - Alt
    - Alt
    - Enter
    - Spc
    - ←
    - ↓
    - ↑
    - →
    - {t: PgDn, s: F12}
  free7:
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
  magic:
    - BT CLR
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - BT CLR ALL
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - RGB SPI
    - RGB SAI
    - RGB HUI
    - RGB BRI
    - RGB TOG
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - Boot
    - RGB SPD
    - RGB SAD
    - RGB HUD
    - RGB BRD
    - RGB EFF
    - ''
    - ''
    - ''
    - ''
    - ''
    - Boot
    - Reset
    - ''
    - ''
    - ''
    - ''
    - ''
    - '&bt_2'
    - '&bt_3'
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - Reset
    - {type: held}
    - ''
    - ''
    - ''
    - ''
    - '&bt_0'
    - '&bt_1'
    - OUT USB
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - {t: factory_test, h: toggle}
  factory_test: ['0', '6', '2', '8', '4', '4', '8', '2', '6', '0', '1', '7', '3', '9', '5', '0', '0', '5', '9', '3', '7', '1', '2', '8', '4', '0', '6', '1', '1', '6', '0', '4', '8', '2', '3', '9', '5', '1', '7', '2', '2', '7', '1', '5', '9', '3', '4', '0', '6', '2', '8', '3', '4', '5', '6', '6', '5', '4', '3', '8', '2', '6', '0', '4', '5', '1', '7', '3', '9', '7', '8', '9', '9', '8', '7', '9', '3', '7', '1', '5']
  none_layout_template: ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
  trans_layout_template:
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
    - {type: trans}
  Combos: ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
combos: []
